version: '2'
services:
  socket:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_ADDRESS=redis://redis:6379
  redis:
    image: redis