version: '2'
services:
  socket:
    image: mhart/alpine-node:8
    working_dir: /usr/app/
    command: [sh, -c, "npm install -g yarn && yarn && yarn start"]
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_ADDRESS=redis://redis:6379
  redis:
    image: redis